const FETCH_STARTED = 'WEATHER/FETCH_STARTED';
const FETCH_SUCCESS = 'WEATHER/FETCH_SUCCESS';
const FETCH_FAIL = 'WEATHER/FETCH_FAIL';
const FETCH_WEATHER_API = 'FETCH_WEATHER_API';

export {
    FETCH_STARTED,
    FETCH_SUCCESS,
    FETCH_FAIL,
    FETCH_WEATHER_API
}